name: AsciiDoc to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Asciidoctor
      run: |
        gem install asciidoctor
        
    - name: Convert AsciiDoc to HTML
      run: |
        asciidoctor -o repo.html repo.adoc
    
    - name: Copy HTML file to repository
      run: |
        cp repo.html $GITHUB_WORKSPACE/repo.html
        
    - name: Commit and push HTML file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add repo.html
        git commit -m "Convert AsciiDoc to HTML"
        git push
