name: AsciiDoc to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        
    - name: Install dependencies
      run: |
        gem install bundler --user-install
        bundle install --path vendor/bundle
        
    - name: Convert AsciiDoc to HTML
      run: bundle exec asciidoctor -o /tmp/repo.html repo.adoc
    
    - name: Move HTML file to repository
      run: mv -f /tmp/repo.html $GITHUB_WORKSPACE/repo.html
        
    - name: Commit and push HTML file
      run: |
        git config --local user.email "valerius.begau@gmail.com"
        git config --local user.name "AssiKalle"
        git add repo.html
        git commit -m "Convert AsciiDoc to HTML"
        git push
