name: AsciiDoc to HTML

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Set up Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        
    - name: Install dependencies
      run: |
        gem install bundler --user-install
        bundle install --path vendor/bundle
        
    - name: Convert AsciiDoc to HTML
      run: bundle exec asciidoctor -o /tmp/index.html repo.adoc
    
    - name: Move HTML file to repository
      run: mv -f /tmp/index.html $GITHUB_WORKSPACE/index.html
        
    - name: Commit and push HTML file
      run: |
        git config --local user.email "valerius.begau@gmail.com"
        git config --local user.name "AssiKalle"
        git add index.html
        git commit -m "Convert AsciiDoc to HTML"
        git push
